name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.233.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6018b30243d57248ae14f3d63b66a05770ad02dcb0fadfd19eb864863b6e47ad"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
