//tool tips

var Cosmetic_Baubles = "Will appear on you. Can be crafted with other Botania baubles to override their appearance. Putting a bauble with a cosmetic override into the crafting grid will remove it from the other bauble.";
var blood_pendants = "Gives the potion effect infused into the pendant. Infusing requires putting it in a Botanical Brewery with all the brew ingredients. The infusion takes 10 times as much Mana as brewing a vial with the same potion.";
var Flügel_Tiaras = "Gives Creative flight by consuming Mana.";
var Pasture_Seeds = "When right-clicked on a Dirt block some of the surrounding Dirt blocks will be turned into the Grass Blocks of their corresponding type.";
val tipsbotania ={
    //wands
    <item:botania:twig_wand> :"Used to rotate Mana Spreaders and view their burst paths, check the Mana stored in a Mana Pool, activate or check the progress of a Botanical Brewery or Runic Altar, and bind generating or functional flora to nearby Mana Pools or Spreaders.",
    <item:botania:rainbow_rod> :"Create bridges in the direction you are looking at.",
    <item:botania:cobble_rod> :"Create a Cobblestone block. Can provide the Rod of the Shifting Crust with Cobblestone.",
    <item:botania:fire_rod> :"Casts a circle of fire, any entity including the caster will burn inside the circle.",
    <item:botania:skydirt_rod> :"All of the Rod of the Lands' abilities and can place a Dirt block in mid-air using mana by facing in the disired direction and right-clicking.",
    <item:botania:obedience_stick> :"Will bind all generating flowers in its range to it when used on any Mana Spreader, and do the same for functional flowers when used on a Mana Pool.",
    <item:botania:dirt_rod> :"Create a Dirt block. Can provide the Rod of the Shifting Crust with Dirt.",
    <item:botania:smelt_rod> :"Smelt targeted blocks",
    <item:botania:divining_rod> :"Show nearby ores.",
    <item:botania:water_rod> :"Create a Water source block. Can also be used to refill a Petal Apothecary.",
    <item:botania:gravity_rod> :"Move and launch mobs and items.",
    <item:botania:exchange_rod> :"Replace blocks of one type in its range with a different one from your inventory.",
    <item:botania:tornado_rod> :"Propels you into the air at a very high velocity.",
    <item:botania:terraform_rod> :"Flatten and level the ground to where you are standing by either removing blocks or placing Dirt.",
    <item:botania:missile_rod> :"Create homing missiles which attack nearby foes.",
    //acessories
    <item:botania:mana_ring> :"Able to store Mana like the Mana Tablet.",
    <item:botania:mana_ring_greater> :"Can store four times as much Mana as the ring of mana.",
    <item:botania:aura_ring> :"Slowly generates Mana and stores it in a Mana Tablet.",
    <item:botania:aura_ring_greater> :"Generates Mana at a significantly faster rate than the Band of Aura.",
    <item:botania:magnet_ring> :"Attracts nearby items.",
    <item:botania:magnet_ring_greater> :"Attracts nearby items better.",
    <item:botania:water_ring> :"Swim like a fish at the cost of Mana.",
    <item:botania:swap_ring> :"Switch the tool youre using with the correct tool. Only works on Mana-using tools.",
    <item:botania:dodge_ring> :"Dodge left or right. Each dodge consumes saturation.",
    <item:botania:pixie_ring> :"Chance to spawn a Pixie which will pursue your attacker.",
    <item:botania:reach_ring> :"Reach is increased by 3 blocks",
    <item:botania:ice_pendant> :"Turn Water you walk over into Ice. Sneak to sink.",
    <item:botania:lava_pendant> :"Will extinguish fire on you.",
    <item:botania:super_lava_pendant> :"Become immune to fire or lava damage.",
    <item:botania:cloud_pendant> :"Double jump. Jumping in mid-air will nullify all fall damage.",
    <item:botania:super_cloud_pendant> :"Triple jump. Jumping in mid-air will nullify all fall damage.",
    <item:botania:travel_belt> :"uses a bit of Mana to buff your movement speed, jump height, and fall-damage resistance. Step assist if not sneaking.",
    <item:botania:super_travel_belt> :"An upgrade to the Soujourner's Sash.",
    <item:botania:speed_up_belt> :"uses a bit of Mana to slowly increase your speed as long as you are moving. Step assist and a 1.5 block jump height increase.",
    <item:botania:knockback_belt> :"Negates any Knockback from outside attacks.",
    <item:botania:holy_cloak> :"Blocks all the damage from a single hit.",
    <item:botania:unholy_cloak> :"Damage all nearby hostile mobs for the same amount of damage you took.",
    <item:botania:balance_cloak> :"Evenly split the damage between the attacker and the target, preventing its bearer from dying in the process.",
    <item:botania:invisibility_cloak> :"Uses Mana to make you and your Trinkets invisible.",
    <item:botania:third_eye> :"Uses Mana to cause nearby mobs to glow, making them visible even through walls.",
    <item:botania:tiny_planet> :"Pulls nearby Mana Bursts into orbits around you.",
    <item:botania:goddess_charm> :"Prevents any explosions around you from destroying blocks,",
    <item:botania:diva_charm> :"Uses Mana to turn attackers on their comrades.",
    <item:botania:itemfinder> :"If you hold an item, the item or container holding that item will emit green clouds. If you sneak, all items on the ground will emit green clouds.",
    <item:botania:bauble_box> :"Can hold up to 24 Baubles or Mana storing items",
    <item:botania:flight_tiara>.withTag({"variant": 0 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 1 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 2 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 3 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 4 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 5 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 6 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 7 as int}) :Flügel_Tiaras,
    <item:botania:flight_tiara>.withTag({"variant": 8 as int}) :Flügel_Tiaras,
    <item:botania:blood_pendant> :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:speed" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:strength" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:haste" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:jump_boost" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:regen" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:regen_weak" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:resistance" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:fire_resistance" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:water_breathing" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:night_vision" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:soul_cross" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:feather_feet" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:emptiness" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:bloodthirst" as string}) :blood_pendants,
    <item:botania:blood_pendant>.withTag({brewKey: "botania:allure" as string}) :blood_pendants,
    <item:botania:cosmetic_black_bowtie> :Cosmetic_Baubles,
    <item:botania:cosmetic_black_tie> :Cosmetic_Baubles,
    <item:botania:cosmetic_red_glasses> :Cosmetic_Baubles,
    <item:botania:cosmetic_puffy_scarf> :Cosmetic_Baubles,
    <item:botania:cosmetic_engineer_goggles> :Cosmetic_Baubles,
    <item:botania:cosmetic_eyepatch> :Cosmetic_Baubles,
    <item:botania:cosmetic_wicked_eyepatch> :Cosmetic_Baubles,
    <item:botania:cosmetic_red_ribbons> :Cosmetic_Baubles,
    <item:botania:cosmetic_pink_flower_bud> :Cosmetic_Baubles,
    <item:botania:cosmetic_polka_dotted_bows> :Cosmetic_Baubles,
    <item:botania:cosmetic_blue_butterfly> :Cosmetic_Baubles,
    <item:botania:cosmetic_cat_ears> :Cosmetic_Baubles,
    <item:botania:cosmetic_witch_pin> :Cosmetic_Baubles,
    <item:botania:cosmetic_devil_tail> :Cosmetic_Baubles,
    <item:botania:cosmetic_kamui_eye> :Cosmetic_Baubles,
    <item:botania:cosmetic_googly_eyes> :Cosmetic_Baubles,
    <item:botania:cosmetic_four_leaf_clover> :Cosmetic_Baubles,
    <item:botania:cosmetic_clock_eye> :Cosmetic_Baubles,
    <item:botania:cosmetic_unicorn_horn> :Cosmetic_Baubles,
    <item:botania:cosmetic_devil_horns> :Cosmetic_Baubles,
    <item:botania:cosmetic_hyper_plus> :Cosmetic_Baubles,
    <item:botania:cosmetic_botanist_emblem> :Cosmetic_Baubles,
    <item:botania:cosmetic_ancient_mask> :Cosmetic_Baubles,
    <item:botania:cosmetic_eerie_mask> :Cosmetic_Baubles,
    <item:botania:cosmetic_alien_antenna> :Cosmetic_Baubles,
    <item:botania:cosmetic_anaglyph_glasses> :Cosmetic_Baubles,
    <item:botania:cosmetic_orange_shades> :Cosmetic_Baubles,
    <item:botania:cosmetic_groucho_glasses> :Cosmetic_Baubles,
    <item:botania:cosmetic_thick_eyebrows> :Cosmetic_Baubles,
    <item:botania:cosmetic_lusitanic_shield> :Cosmetic_Baubles,
    <item:botania:cosmetic_tiny_potato_mask> :Cosmetic_Baubles,
    <item:botania:cosmetic_questgiver_mark> :Cosmetic_Baubles,
    <item:botania:cosmetic_thinking_hand> :Cosmetic_Baubles,
    //resourses
    <item:botania:fertilizer> :"When right-clicked on any piece of dirt or grass, it will spawn three to four Mystical Flowers in the vicinity.",
    <item:botania:overgrowth_seed> :"Right-click on a Grass Block to create Enchanted Soil.",
    <item:botania:mana_cookie> :"Gives Saturation for 20 ticks, effectively restoring all hunger points.",
    <item:botania:virus_necrodermal> :"When used on a tamed Horse (including donkeys and mules), it will turn it into a zombie horse, doubling its health and speed, increasing jump height by 50%, and nullifying all fall damage taken by the horse. The transformed horse will drop the horse armor it wears; mules and donkeys will drop their attached chests and their contents.",
    <item:botania:virus_nullodermal> :"When used on a tamed Horse (including donkeys and mules), it will turn it into a skeleton horse, doubling its health and speed, increasing jump height by 50%, and nullifying all fall damage taken by the horse. The transformed horse will drop the horse armor it wears; mules and donkeys will drop their attached chests and their contents.",
    <item:botania:podzol_seeds> :"When used on Dirt or Grass, turns blocks nearby into Podzol. When used on a floating flower, the soil of the flower will be turned to Podzol and the floating flower will pick up items as if it was planted on Podzol— with a 5 tick delay.",
    <item:botania:mycelium_seeds> :"When used on Dirt or Grass, turns blocks nearby into Mycelium. When used on a floating flower, the soil of the flower will be turned to Mycelium and the floating flower will pick up items as if it was planted on Mycelium— with a 10 tick delay.",
    <item:botania:grass_seeds> :Pasture_Seeds,
    <item:botania:dry_seeds> :Pasture_Seeds,
    <item:botania:golden_seeds> :Pasture_Seeds,
    <item:botania:vivid_seeds> :Pasture_Seeds,
    <item:botania:scorched_seeds> :Pasture_Seeds,
    <item:botania:infused_seeds> :Pasture_Seeds,
    <item:botania:mutated_seeds> :Pasture_Seeds,
    //mana stuff
    <item:botania:mana_bottle> :"Briefly acquire positive or negative effects. Some events may occur.",
    <item:botania:black_lotus> :"A single-use Mana container. Throw into a Mana Pool to get mana.",
    <item:botania:blacker_lotus> :"A single-use Mana container. Throw into a Mana Pool to get more mana.",
    <item:botania:mana_mirror> :"Provides Mana from the linked Mana Pool to Mana-using items in your inventory. Shift right-clicking a Mana Pool with the Mirror will link the two together.",
    <item:botania:mana_tablet> :"Transport Mana. Dropping into a Mana Pool will transfer Mana from one to the other, depending on which way Mana is flowing—this can be viewed while wielding a Wand of the Forest. Shift right-clicking with the Wand will change the flow of Mana.",
    <item:botania:mana_gun> :"Shoots Mana bursts using Mana. Compared to a Mana Spreader, Mana bursts fired by the blaster are 5 times faster, but hold 25% less Mana. Mana Lenses can be used with the Blaster to provide it with their effects.",
    //Brewery
    <item:botania:incense_plate> :"Once an Incense Stick is placed onto it, right-clicking with a Flint and Steel will ignite the stick. This can also be done with a Mana burst with the Kindle Lens. Also accept items from a Hopper or any other inputting mechanism. It will also emit Comparator signals, where 1 signals there is a stick present, and 2 signals the stick is currently burning.",
    <item:botania:vial> :"A container for brews created from the Botanical Brewery. It can hold 4 doses of a brew.",
    <item:botania:flask> :"A container for brews created in the Botanical Brewery. It can hold 6 doses of a brew. When drinking a brew from an Alfglass Flask, the speed of which the dose is consumed is faster than from a Managlass Vial. However, the cost of Mana for brewing is doubled when using an Alfglass Flask.",
     :"",
     :"",
     :"",
     :"",
     :"",
     :"",
     :"",
    


}.addTips();