global.colors = ['white', 'orange', 'magenta', 'light_blue', 'yellow', 'lime', 'pink', 'gray', 'light_gray', 'cyan', 'purple', 'magenta', 'blue', 'brown', 'green', 'red', 'black']
global.itemsToHide = []
global.categoriesToHide = []
global.itemsToRemove = []
global.itemTooltips = []